apiVersion: gcp.platform.upbound.io/v1alpha1
kind: XGKE
metadata:
  name: gcp-gke-workload-identity
spec:
  parameters:
    id: gcp-gke-workload-identity
    region: us-west2
    version: latest
    nodes:
      count: 3
      instanceType: n1-standard-4
  writeConnectionSecretToRef:
    name: gcp-gke-workload-identity-kubeconfig
    namespace: upbound-system
